# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

Name = "ask-asya"
License = "MIT"
Licenselink = "https://github.com/asya999/askAsya/blob/master/LICENSE.md"
Description = "Ask Asya Theme"
Homepage = "http://askAsya.com/"
Tags = ["tags", "categories"]
Features = ["mongodb", "nosql"]
Min_version = 0.14

[Author]
  Name = "Asya Kamsky"
  Homepage = "http://askasya.com"

[Params]
  Title = "Ask Asya"
  Tagline = "Answers to your burning questions about MongoDB"
  GitHubUser = asya999
  DateForm = "Jan 2 2006"

# If porting an existing theme
[original]
  name = "lanyon"
  homepage = ""
  repo = "https://github.com/tummychow/lanyon-hugo"
